### ISSUE TITLE
support for initializing conda environment

### ISSUE THREAD

**Issue by edublancas** [takluyver/bash_kernel#130]
I'm using jupyter-book, bash-kernel, and readthedocs for a project.

I noticed that when starting up the bash kernel, conda wouldn't be properly configured, so I added a `conda activate` cell at the top of my notebook, but this doesn't work https://github.com/takluyver/bash_kernel/issues/97. So next thing I thought was that the bash kernel could initialize with conda already configured.

I forked the project and [made it work.](https://github.com/edublancas/bash_kernel/commit/77a5491a8d9b0b6cc0c3ba421b20bc5c4a26cf49)

Essentially, it adds a new option to the install command:

```sh
python -m bash_kernel.install --sys-prefix --conda-activate
```

This ensures that whenever the kernel starts, it's already configured to use the conda environment where bash_kernel is installed.

Is this something that this project would like to incorporate? Happy to get feedback on what I did and open a PR

**Comment by kdm9** [comment]
Thanks for this!

I agree with this issue but am not a massive fan of this way of fixing it, as AFAICT it hardcodes the conda environment to be activated.  #97 should in theory be fixed in the main branch, have you tried installing from git? I should cut another release (seems I forgot to after merging that fix), but I might wait until you confirm that the main issue with conda is fixed by #125

With that change, you need to do conda activate <envname> in the first cell, but thereafter it should behalf more or less like a typical bash shell.

In any case, I'll ensure that bash_kernel works well with conda -- it is currently for me with #125, but if it still doesn't work for you we can make it work :)

Best,
K

**Comment by edublancas** [comment]
thanks for the feedback! @kdm9 

I agree my approach was very opinionated. my fix is working for my team for now but I'd like to move forward with the official solution. So once I find some time I'll test it and share my feedback!

Closing this!

**Comment by kdm9** [comment]
Cool, thanks for testing. As I said, if it's not working for your team, then please reopen this and we'll find a general solution.

Best,
K
