### ISSUE TITLE
jupyter notebook as ssh client

### ISSUE THREAD

**Issue by aaronsgithub** [takluyver/bash_kernel#131]
This might be dumb, but I'm trying to explore the idea of using this kernel as a starting point to turn jupyter notebooks into an ssh client of sorts.

The motivation being that capturing the execution of shell commands over an ssh connection inside a notebook would be a convenient way to document a server, whilst providing interactive feedback from the server itself e.g. to check logs etc.

It almost works:
![image](https://github.com/takluyver/bash_kernel/assets/5004394/fab8204b-504d-4d7c-948a-d4e3a2b5a3b0)

The first hurdle is that, due to the limitations with accepting input via jupyter notebooks, you have to have passwordless authentication which isn't a big deal if I'm using key authentication.

So I can successfully connect and execute commands. The problem now it that I have to interrupt the kernel (twice) for the output of the command to be written to the cell output.

Any idea why commands over an ssh connection would block?

**Comment by takluyver** [comment]
I'm surprised it works even that well, to be honest. bash_kernel works by setting the prompt to a special value which it can look for in the output to tell when a cell has finished executing:

https://github.com/takluyver/bash_kernel/blob/9049a84bbe53f3482c84ab7ff8b063b812ac1a48/bash_kernel/kernel.py#L101-L102

Your ssh session won't use that prompt, so from bash_kernel's perspective, it's stuck executing the first cell.

You might be able to get this to work by passing the `PS1` and `PS2` variables through ssh to the bash that's started on the remote side. Something like: `ssh user@host "PS1=$PS1 PS2=$PS2 bash"` (I haven't tried this).

**Comment by aaronsgithub** [comment]
> I'm surprised it works even that well

I was surprised I got that far too 😂.

I'll close this issue but I'll probably hack on it for a bit to see what's possible.

**Comment by kdm9** [comment]
One possibility would be to use `ssh host -tt bash` as a fake "bash interpreter", which we then also send the usual init code to including mucking around with PS1. It would very much not handle disconnects or other thing that never happen with real bash, but it could "work", for a loose definition of working.

More seriously, I use remote jupyterlab via ssh forwarding daily, and can recommend that as a solution to this problem.

**Comment by aaronsgithub** [comment]
Thanks for the suggestion.

Yes, port forwarding jupyter is really handy but the desire was to use have a notebook act as an ssh client which doesn't require jupyter to be installed on the server.

I absolutely do not need this in my life but I want it 🙃

**Comment by nnWhisperer** [comment]
Hello, I'm also interested in this feature, I think it makes sense. How did you guys proceed with?

**Comment by kdm9** [comment]
@nnWhisperer see my previous comment: this is something that  I am not opposed to, but I have no need for and I am too busy to implement this for fun. I would welcome a PR that provides a way to set the full bash command to be used as the interpreter, which would allow using `ssh user@host bash` or `/werid/path-to/special/bash` instead of just `bash`.

Any logic around fully supporting SSH connections, detecting and fixing disconnects, password handling etc I think is out of scope. `bash_kernel` is robust through simplicity (hopefully!). I'm happy to be convinced otherwise though, if someone comes up with a simple way to handle all of that complexity. However, the jupyter kernel interface is pretty simple, so probably the best way forward would be writing paramiko-backed kernel that does all of the ssh connection handling properly, rather than whatever jank we would need to do here. Something like that might already exist, I don't know as I have no need for it as explained above.
