### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by sindhus** [takluyver/bash_kernel#17]
from PySide import QtGui, QtCore, QtSvg
ImportError: dlopen(/Users/sindhus/Library/Python/2.7/lib/python/site-packages/PySide/QtGui.so, 2): Library not loaded: libpyside-python2.7.1.2.dylib
  Referenced from: /Users/sindhus/Library/Python/2.7/lib/python/site-packages/PySide/QtGui.so
  Reason: image not found

How do I fix this? I have pyqt and pyside installed.
Thanks!

**Comment by takluyver** [comment]
Hi - bash_kernel doesn't use any Qt libraries, so I guess you're trying to start it in the IPython Qt console? If so, you should be able to use one of the other frontends (`ipython notebook` or `ipython console`).

It looks like your pyside installation has a problem. If IPython finds PySide, it will use that over PyQt. So it might work if you remove PySide, because then it will try PyQt instead.

I don't know much about installing stuff on macs, so if that doesn't solve the problem, you might want to try asking on stackoverflow, or the ipython-dev mailing list.

**Comment by sindhus** [comment]
Then why does the Readme say to start with "ipython qtconsole --kernel bash"?

**Comment by takluyver** [comment]
It's just an example. I'll try to make it clearer.

Using the notebook in 3.x, there's no need for any special command line argument. Once you've installed bash_kernel, an option for a Bash notebook should appear on the 'New' menu.
