### ISSUE TITLE
Display Bash prompt

### ISSUE THREAD

**Issue by eliemichel** [takluyver/bash_kernel#38]
At least displaying `pwd` could be a nice feature.

**Comment by takluyver** [comment]
The prompts are defined by the frontend you're using, not the kernel. I doubt that the notebook prompts are going to do something like that.

**Comment by eliemichel** [comment]
Ok, Thanks.
I was wondering whether somebody was aware of such frontend plugin.

**Comment by takluyver** [comment]
I don't know of any. It's not trivial, because the kernel has to be involved as well - the frontend doesn't know what the kernel's working directory is.

You might be interested in [redsnail](https://github.com/takluyver/redsnail) - it's a side project of mine that integrates a terminal running bash with status panels that are updated with each bash prompt.

**Comment by eliemichel** [comment]
Oh this is great! I actually kinda started to work on something like this, but I might consider using yours instead. =)

However, what I was looking for with the Bash kernel is to have kind of a systematic way to log my experiments. I don't want to log any command as I do a lot of trial error, so the notebook was a good solution.
