### ISSUE TITLE
can't use git push / git pull

### ISSUE THREAD

**Issue by ssokhey** [takluyver/bash_kernel#63]
I was trying to create a jupyter notebook on git usage. But when I use:

> git push origin master

It just keeps processing. It should actually ask the git username then password.

Is there any workaround for this or am I missing something? 

OS: Linux 14.04.5

**Comment by takluyver** [comment]
See also #60 - it's a general limitation due to the way terminals work and the way Jupyter works. We can't tell when a subprocess is waiting for input. Sorry, I know that's a pretty big limitation for using bash.

The workaround for this case would be to set up ssh keys so you can push/pull without needing to type in a username and password.

**Comment by ssokhey** [comment]
It's okay. 
I will set-up the ssh keys for git puss/pull.

Thanks for the reply.
